http:
  routers:
    grafana:
      rule: "Host(`grafana.next.erp.ojie.dev`)"
      entryPoints:
        - websecure
      service: grafana
      tls:
        certResolver: letsencrypt

  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"