http:
  routers:
    minio:
      rule: "Host(`storage.next.erp.ojie.dev`)"
      entryPoints:
        - websecure
      service: minio
      tls:
        certResolver: letsencrypt

  services:
    minio:
      loadBalancer:
        servers:
          - url: "http://minio:9000"